#!/bin/bash
host="https://backoffice.bangladeshguardian.com"
paths=(
  "/api/upload"
  "/api/v1/upload"
  "/api/media/upload"
  "/api/images/upload"
  "/api-en/upload"
  "/api-en/media/upload"
  "/api-en/image/upload"
  "/api-en/images/upload"
  "/media/upload"
  "/images/upload"
  "/upload"
  "/public/upload"
  "/storage/upload"
  "/admin/upload"
  "/admin/media/upload"
  "/admin/images/upload"
  "/laravel-filemanager/upload"
  "/filemanager/upload"
  "/ckeditor/upload"
  "/tinymce/upload"
  "/fckeditor/upload"
  "/kindeditor/upload"
  "/file/upload"
  "/api/file/upload"
  "/api-en/file/upload"
  "/upload-image"
  "/upload-file"
  "/save-image"
  "/api-en/save-image"
)

for p in "${paths[@]}"; do
  echo -n "Testing $p: "
  curl -s -o /dev/null -w "%{http_code}" -X POST -F "file=@package.json" "$host$p"
  echo ""
done
